# fly.toml app configuration file generated for chat-app-rework-7cihua on 2024-11-21T11:24:01Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chat-app-rework-7cihua'
primary_region = 'lax'

[build]
buildpacks = ["heroku/python", "heroku/nodejs"]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

  [env]
  DATABASE_URL = "postgres://chat_app_rework_7cihua:HqoGgAsxwW2PqxW@long-shape-8614.flycast:5432/chat_app_rework_7cihua?sslmode=disable"

